name: CI

on:
  push:
    branches:
      - main
  pull_request: {}


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys:
            - ${{ runner.os }}-go-

      - run: make fmt

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint@v1.46.2
        with:
          version: v1.46.2
          only-new-issues: true
          skip-go-installation: true

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys:
            - ${{ runner.os }}-go-

      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-bin-${{ hashFiles('**/go.sum') }}
          restore-keys:
            - ${{ runner.os }}-go-build-

#  Coverage:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.18
#
#      - uses: actions/cache@v3
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys:
#            - ${{ runner.os }}-go-
#
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Generate coverage report
#        run: make test-coverage
#
#      - name: Upload coverage
#        uses: codecov/codecov-action@v3
#        with:
#          fail_ci_if_error: false

